"""added openai threads and assistant table

Revision ID: 643b118cbfa7
Revises: 514a8b20792d
Create Date: 2024-10-10 22:03:32.380651

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "643b118cbfa7"
down_revision = "514a8b20792d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "openai_assistants",
        sa.Column("openai_assistant_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("openai_assistant_id"),
    )
    op.create_index(
        op.f("ix_openai_assistants_openai_assistant_id"),
        "openai_assistants",
        ["openai_assistant_id"],
        unique=False,
    )
    op.create_table(
        "openai_threads",
        sa.Column("openai_thread_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("openai_thread_id"),
    )
    op.create_index(
        op.f("ix_openai_threads_openai_thread_id"),
        "openai_threads",
        ["openai_thread_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_openai_threads_openai_thread_id"), table_name="openai_threads"
    )
    op.drop_table("openai_threads")
    op.drop_index(
        op.f("ix_openai_assistants_openai_assistant_id"), table_name="openai_assistants"
    )
    op.drop_table("openai_assistants")
    # ### end Alembic commands ###
